"""Create a persistent local Qdrant index from sentence-window chunks."""
from __future__ import annotations

import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from qdrant_client import QdrantClient
from qdrant_client.models import (
    Distance,
    FieldCondition,
    Filter,
    FilterSelector,
    MatchAny,
    PointStruct,
    VectorParams,
)


KNOWLEDGE_ROOT = Path(__file__).resolve().parent
MODEL_PATH = KNOWLEDGE_ROOT / "embedding_model" / "bge-small-zh-v1.5"
CHUNK_PATH = KNOWLEDGE_ROOT / "chunks" / "sentence_window_nodes.jsonl"
QDRANT_PATH = KNOWLEDGE_ROOT / "qdrant_db"
COLLECTION_NAME = "knowledge_chunks"


@dataclass(frozen=True)
class IndexBuildResult:
    """Summary of one completed local index build."""

    collection_name: str
    indexed_nodes: int
    vector_size: int
    qdrant_path: Path
    source_chunk_counts: dict[str, int]


def load_chunk_records(chunk_path: Path = CHUNK_PATH) -> list[dict[str, Any]]:
    """Load JSONL nodes generated by ``chunk_embedding.py``.

    Args:
        chunk_path: Sentence-window JSONL artifact path.

    Returns:
        Serialized LlamaIndex node records.

    Raises:
        FileNotFoundError: If the chunk artifact does not exist.
        ValueError: If a JSONL row is invalid or lacks node text.
    """
    if not chunk_path.exists():
        raise FileNotFoundError(f"未找到切分结果，请先运行文档切分：{chunk_path}")

    records: list[dict[str, Any]] = []
    for line_number, line in enumerate(chunk_path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            raise ValueError(f"切分结果第 {line_number} 行不是有效 JSON") from exc
        if not isinstance(record, dict) or not isinstance(record.get("text"), str):
            raise ValueError(f"切分结果第 {line_number} 行缺少节点文本")
        records.append(record)
    return records


def build_local_qdrant_index(
    chunk_path: Path = CHUNK_PATH,
    model_path: Path = MODEL_PATH,
    qdrant_path: Path = QDRANT_PATH,
    *,
    collection_name: str = COLLECTION_NAME,
) -> IndexBuildResult:
    """Embed sentence-window nodes and rebuild a persistent local collection.

    Args:
        chunk_path: JSONL nodes generated during the chunking stage.
        model_path: Local HuggingFace embedding model directory.
        qdrant_path: Local Qdrant storage directory.
        collection_name: Qdrant collection to rebuild from the current chunks.

    Returns:
        Collection name, indexed node count, vector dimension, and storage path.

    Raises:
        ValueError: If the chunk artifact contains no indexable nodes.
        FileNotFoundError: If the local GGUF model is absent.
        RuntimeError: If HuggingFace embedding dependencies are unavailable.
    """
    records = load_chunk_records(chunk_path)
    if not records:
        raise ValueError("切分结果为空，无法建立嵌入索引")
    if not (model_path / "config.json").is_file():
        raise FileNotFoundError(f"未找到本地嵌入模型：{model_path}")

    model = _load_huggingface_embedding_model(model_path)
    texts = [record["text"] for record in records]
    vectors = _embed_texts(model, texts)
    if len(vectors) != len(records) or not vectors or not vectors[0]:
        raise RuntimeError("嵌入模型返回的向量数量或维度无效")

    vector_size = len(vectors[0])
    if any(len(vector) != vector_size for vector in vectors):
        raise RuntimeError("嵌入模型返回了不一致的向量维度")

    qdrant_path.mkdir(parents=True, exist_ok=True)
    client = QdrantClient(path=str(qdrant_path))
    try:
        if client.collection_exists(collection_name):
            client.delete_collection(collection_name)
        client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(size=vector_size, distance=Distance.COSINE),
        )
        client.upsert(
            collection_name=collection_name,
            points=[
                PointStruct(
                    id=index,
                    vector=vector,
                    payload=_node_payload(record),
                )
                for index, (record, vector) in enumerate(zip(records, vectors))
            ],
        )
    finally:
        client.close()
    return IndexBuildResult(
        collection_name=collection_name,
        indexed_nodes=len(records),
        vector_size=vector_size,
        qdrant_path=qdrant_path,
        source_chunk_counts=dict(
            Counter(
                str(record.get("metadata", {}).get("source_file") or "")
                for record in records
            )
        ),
    )


def _load_huggingface_embedding_model(model_path: Path) -> Any:
    """Load the repository's local BGE model with HuggingFaceEmbeddings."""
    try:
        from langchain_huggingface import HuggingFaceEmbeddings
    except ImportError as exc:
        raise RuntimeError(
            "缺少 langchain-huggingface 或 sentence-transformers，无法加载本地嵌入模型"
        ) from exc
    return HuggingFaceEmbeddings(
        model_name=str(model_path),
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},
    )


def _embed_texts(model: Any, texts: list[str]) -> list[list[float]]:
    """Generate normalized document embeddings with HuggingFaceEmbeddings."""
    vectors = model.embed_documents(texts)
    if not isinstance(vectors, list):
        raise RuntimeError("嵌入模型返回格式无效")
    return [list(map(float, vector)) for vector in vectors]


def delete_document_vectors(
    document_ids: set[str],
    qdrant_path: Path = QDRANT_PATH,
    *,
    collection_name: str = COLLECTION_NAME,
) -> None:
    """Delete all indexed vectors belonging to the selected document UUIDs.

    Args:
        document_ids: Stable document UUIDs stored in Qdrant payload metadata.
        qdrant_path: Local Qdrant storage directory.
        collection_name: Collection holding knowledge document vectors.
    """
    if not document_ids:
        return
    client = QdrantClient(path=str(qdrant_path))
    try:
        if not client.collection_exists(collection_name):
            return
        client.delete(
            collection_name=collection_name,
            points_selector=FilterSelector(
                filter=Filter(
                    must=[
                        FieldCondition(
                            key="document_id",
                            match=MatchAny(any=sorted(document_ids)),
                        )
                    ]
                )
            ),
        )
    finally:
        client.close()


def _node_payload(record: dict[str, Any]) -> dict[str, Any]:
    """Keep retrieval text, sentence context, and provenance in Qdrant."""
    metadata = record.get("metadata") if isinstance(record.get("metadata"), dict) else {}
    return {
        "node_id": str(record.get("id_") or ""),
        "document_id": str(metadata.get("document_id") or ""),
        "text": record["text"],
        "window": str(metadata.get("window") or ""),
        "original_text": str(metadata.get("original_text") or ""),
        "source_file": str(metadata.get("source_file") or ""),
        "source_path": str(metadata.get("source_path") or ""),
    }


if __name__ == "__main__":
    result = build_local_qdrant_index()
    print(
        f"已建立 Qdrant 索引：{result.collection_name}，"
        f"节点 {result.indexed_nodes} 个，维度 {result.vector_size}，"
        f"路径：{result.qdrant_path}"
    )
